# Generated by Django 5.1.6 on 2025-04-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAccess', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('lab', 'Lab'), ('ambulance', 'Ambulance')], max_length=100),
        ),
    ]
