# Generated by Django 5.2 on 2025-04-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAccess', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firebase_registration_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
