# Generated by Django 5.2 on 2025-06-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginAccess', '0004_user_email_otp_user_otp_user_verification_expiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_reset_password',
            field=models.BooleanField(default=False),
        ),
    ]
