# Generated by Django 5.2 on 2025-04-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labs', '0002_labtype_labprofile_testtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labprofile',
            name='lab_types',
        ),
        migrations.AddField(
            model_name='labtype',
            name='tests',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='TestType',
        ),
    ]
