# Generated by Django 5.2 on 2025-04-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labs', '0003_remove_labprofile_lab_types_labtype_tests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labprofile',
            name='lab_types',
            field=models.ManyToManyField(related_name='labs', to='Labs.labtype'),
        ),
    ]
