# Generated by Django 5.2 on 2025-04-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labs', '0005_remove_labprofile_lab_types_labtype_lab_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtype',
            name='lab_profile',
        ),
        migrations.AddField(
            model_name='labprofile',
            name='lab_types',
            field=models.ManyToManyField(related_name='labs', to='Labs.labtype'),
        ),
    ]
