# Generated by Django 5.2 on 2025-04-22 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labs', '0006_remove_labtype_lab_profile_labprofile_lab_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labprofile',
            name='lab_types',
        ),
        migrations.AddField(
            model_name='labtype',
            name='lab_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lab_types', to='Labs.labprofile'),
            preserve_default=False,
        ),
    ]
