# Generated by Django 5.2 on 2025-04-23 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labs', '0008_alter_labtest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='lab_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='Labs.labprofile'),
            preserve_default=False,
        ),
    ]
