# Generated by Django 5.2 on 2025-04-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labs', '0009_labtest_lab_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='registration_number',
            field=models.CharField(default=213, editable=False, max_length=10),
        ),
    ]
