# Generated by Django 5.2 on 2025-04-27 18:32

import Labs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labs', '0010_labtest_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='registration_number',
            field=models.CharField(default=Labs.models.generate_registration_number, editable=False, max_length=10, unique=True),
        ),
    ]
