# Generated by Django 5.2 on 2025-05-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labs', '0011_alter_labtest_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labreport',
            name='file',
            field=models.FileField(max_length=50, upload_to='reports/'),
        ),
    ]
