# Generated by Django 5.2 on 2025-06-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labs', '0012_alter_labreport_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtype',
            name='lab_profile',
        ),
        migrations.AddField(
            model_name='labprofile',
            name='lab_types',
            field=models.ManyToManyField(related_name='labs', to='Labs.labtype'),
        ),
    ]
