# Generated by Django 5.2 on 2025-06-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labs', '0013_remove_labtype_lab_profile_labprofile_lab_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labprofile',
            name='lab_types',
        ),
        migrations.AddField(
            model_name='labprofile',
            name='lab_types',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
