# Generated by Django 5.2 on 2025-06-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labs', '0014_remove_labprofile_lab_types_labprofile_lab_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labprofile',
            name='lab_types',
        ),
        migrations.AddField(
            model_name='labprofile',
            name='lab_types',
            field=models.ManyToManyField(related_name='labs', to='Labs.labtype'),
        ),
    ]
