# Generated by Django 5.2 on 2025-06-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labs', '0015_remove_labprofile_lab_types_labprofile_lab_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labreport',
            name='file',
            field=models.FileField(max_length=255, upload_to='reports/'),
        ),
    ]
