# Generated by Django 5.2 on 2025-06-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labs', '0016_alter_labreport_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='labprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
