# Generated by Django 5.2 on 2025-06-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labs', '0018_labavailability'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='labavailability',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='labavailability',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
