# Generated by Django 5.2 on 2025-06-25 10:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Labs', '0020_alter_labavailability_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='labavailability',
            unique_together={('lab', 'date', 'start_time', 'end_time')},
        ),
    ]
