version: '3.8'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
  
  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
  
  web:
    build: .
    command: gunicorn MyClinic.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - ./media:/app/media
      - ./static:/app/static
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
  celery:
    build: .
    command: celery -A MyClinic worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    command: celery -A MyClinic beat --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db