# Generated by Django 5.2 on 2025-07-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to='notifications/')),
                ('url', models.URLField(blank=True, null=True)),
                ('tags', models.CharField(choices=[('health_tip', 'Health Tip'), ('general', 'General'), ('promotion', 'Promotion'), ('alert', 'Alert')], default='general', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
