# Generated by Django 5.2 on 2025-07-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
