# Generated by Django 5.2 on 2025-07-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0002_alter_notification_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='notifications/'),
        ),
    ]
