# Generated by Django 5.2 on 2025-07-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminAnalytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costingconfig',
            name='period',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('yearly', 'Yearly')], default='monthly', max_length=20),
        ),
    ]
