# Generated by Django 5.2 on 2025-07-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminAnalytics', '0002_alter_costingconfig_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costingconfig',
            name='period',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('yearly', 'Yearly')], max_length=20, null=True),
        ),
    ]
