# Generated by Django 5.2 on 2025-04-23 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=100)),
                ('specialist', models.CharField(max_length=100)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('clinic_name', models.CharField(max_length=100)),
                ('clinic_address', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('profile_image', models.TextField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Doctor_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
