# Generated by Django 5.1.6 on 2025-04-21 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorAccess', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorregistration',
            old_name='doctor_id',
            new_name='doctor',
        ),
        migrations.RemoveField(
            model_name='doctorregistration',
            name='user_id',
        ),
    ]
