# Generated by Django 5.2 on 2025-04-24 14:43

import DoctorAccess.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorAccess', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=100)),
                ('specialist', models.CharField(max_length=100)),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_number', models.CharField(max_length=100)),
                ('patient_age', models.CharField(max_length=20)),
                ('patient_gender', models.CharField(max_length=50)),
                ('date_of_visit', models.DateField()),
                ('shift', models.CharField(max_length=50)),
                ('visit_time', models.TimeField()),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('registration_number', models.CharField(default=DoctorAccess.models.generate_registration_number, editable=False, max_length=10, unique=True)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Doctor_id_appointment', to=settings.AUTH_USER_MODEL)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
