# Generated by Django 5.2 on 2025-04-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorAccess', '0002_doctorappointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorappointment',
            name='patient_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='doctorappointment',
            name='shift',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night')], max_length=50),
        ),
    ]
