# Generated by Django 5.1.6 on 2025-04-23 05:33

import DoctorAccess.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorAccess', '0003_doctorappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorappointment',
            name='registration_number',
            field=models.CharField(default=DoctorAccess.models.generate_registration_number, editable=False, max_length=10, unique=True),
        ),
    ]
