# Generated by Django 5.2 on 2025-04-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorAccess', '0004_doctoravailability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctoravailability',
            old_name='availabe',
            new_name='available',
        ),
        migrations.RenameField(
            model_name='doctoravailability',
            old_name='time',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='doctorappointment',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctorappointment',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='end_time',
            field=models.TimeField(default='08:00:00'),
        ),
    ]
