# Generated by Django 5.2 on 2025-04-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorAccess', '0005_rename_availabe_doctoravailability_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoravailability',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
