# Generated by Django 5.2 on 2025-04-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorAccess', '0006_alter_doctoravailability_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorregistration',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
