# Generated by Django 5.2 on 2025-05-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorAccess', '0007_alter_doctorregistration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorappointment',
            name='delay_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
