# Generated by Django 5.2 on 2025-06-12 09:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorAccess', '0008_doctorappointment_delay_minutes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctoravailability',
            unique_together={('doctor', 'date', 'start_time', 'end_time', 'shift')},
        ),
    ]
