# Generated by Django 5.2 on 2025-06-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorAccess', '0009_alter_doctoravailability_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorregistration',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
