# Generated by Django 5.2 on 2025-06-30 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorAccess', '0010_doctorregistration_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorregistration',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Doctor_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
