# Generated by Django 5.2 on 2025-07-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorAccess', '0011_alter_doctorregistration_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
