# Generated by Django 5.2 on 2025-04-25 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0004_patientprofile_gender_insurance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AmbulanceRequest',
        ),
    ]
