# Generated by Django 5.1.6 on 2025-04-24 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmbulanceAccess', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ambulance',
            old_name='vehicle_numer',
            new_name='vehicle_nubmer',
        ),
    ]
