# Generated by Django 5.1.6 on 2025-04-24 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmbulanceAccess', '0002_rename_vehicle_numer_ambulance_vehicle_nubmer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ambulance',
            old_name='vehicle_nubmer',
            new_name='vehicle_number',
        ),
    ]
