# Generated by Django 5.1.6 on 2025-04-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmbulanceAccess', '0003_rename_vehicle_nubmer_ambulance_vehicle_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulance',
            name='vehicle_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
