# Generated by Django 5.2 on 2025-06-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmbulanceAccess', '0004_alter_ambulance_vehicle_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
